Enhance/Pages/AllProjects.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;
using System.Collections.Generic;

namespace Enhance.Pages
{
    public class AllProjectsModel : PageModel
    {
        public List<Project> Projects { get; set; }

        public void OnGet()
        {
            ViewData["Page"] = "Show";
            Projects = new List<Project>();

            string connectionString = "Server=localhost;Database=ZEUS;Uid=root;Pwd=azxcvbnmlkjhgfds;";
            string query = $@"
        SELECT p.*,
               (SELECT COUNT(*) FROM BID b WHERE b.Project_ID = p.Number) AS Bid
        FROM POST_PROJECT p
        WHERE p.User_Id = {LoginModel.UserId}";

            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                connection.Open();

                MySqlCommand command = new MySqlCommand(query, connection);
                MySqlDataReader reader = command.ExecuteReader();

                while (reader.Read())
                {
                    Project project = new Project
                    {
                        Name = reader.GetString("ProjectName"),
                        Number = reader.GetInt32("Number"),
                        Price = reader.GetInt32("Price"),
                        Type = reader.GetString("CurrencyType"),
                        PostDate = reader.GetDateTime("PostDate").ToString("yyyy-MM-dd"),
                        Status = reader.GetInt32("Status"),
                        Bid = reader.GetInt32("Bid") // Read the bid count from the subquery
                    };

                    Projects.Add(project);
                }

                reader.Close(); // Close the reader after the while loop
            }


            using (MySqlConnection connection = new MySqlConnection(connectionString))
            {
                connection.Open();

                foreach (Project project in Projects)
                {
                    string cidQuery = $"SELECT * FROM CID WHERE ProjectId = {project.Number} AND Cid IS NOT NULL";
                    MySqlCommand cidCommand = new MySqlCommand(cidQuery, connection);
                    MySqlDataReader cidReader = cidCommand.ExecuteReader();

                    if (cidReader.HasRows)
                    {
                        project.Status = 2;
                    }

                    cidReader.Close();
                }

            }
        }

        public IActionResult OnPost()
        {
            int number = int.Parse(Request.Form["Number"]);

            string connectionString = "Server=localhost;Database=ZEUS;Uid=root;Pwd=azxcvbnmlkjhgfds;";
            string query = $"DELETE FROM POST_PROJECT WHERE Number = {number}";

            using (MySqlConnection connection = new MySqlConnection(connectionString))
            using (MySqlCommand command = new MySqlCommand(query, connection))
            {
                connection.Open();
                command.ExecuteNonQuery();
                connection.Close();
            }

            return Redirect("/AllProjects"); // or return any other appropriate response
        }
    }

    public class Project
    {
        public string Name { get; set; }
        public int Number { get; set; }
        public int Price { get; set; }
        public string Type { get; set; }
        public string PostDate { get; set; }
        public int Bid { get; set; } // New property to store the row count
        public int Status { get; set; }
        // Add more properties from the table as needed
    }
}

Enhance/Pages/AlreadyExist.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Enhance.Pages
{
    public class AlreadyExistModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Enhance/Pages/Applicant.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using MySql.Data.MySqlClient;
using MailKit.Net.Smtp;
using MailKit.Security;
using MimeKit;


namespace Enhance.Pages
{
    public class EmailData1
    {
        public string? GroupName1 { get; set; }
        public string? Subject { get; set; }
    }
    // send a email to notify that member has been removed from the group
    public class EmailSender1
    {
        private readonly string smtpServer = "smtp.gmail.com";
        private readonly int smtpPort = 587;
        private readonly string smtpUsername = "agreharshit610@gmail.com";
        private readonly string smtpPassword = "lbqxavlpxnewvczt";

        public void SendEmail(string recipientEmail, EmailData1 emailData1)
        {
            try
            {
                var message = new MimeMessage();
                message.From.Add(new MailboxAddress("Sender Name", smtpUsername));
                message.To.Add(new MailboxAddress("Recipient Name", recipientEmail));
                message.Subject = $"{emailData1.Subject}";

                // Construct the email body using the project data
                message.Body = new TextPart("plain")
                {
                    Text = $"You application for {emailData1.GroupName1} has not been accepted"
                };

                using (var client = new SmtpClient())
                {
                    client.Connect(smtpServer, smtpPort, SecureSocketOptions.StartTls);
                    client.Authenticate(smtpUsername, smtpPassword);
                    client.Send(message);
                    client.Disconnect(true);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Failed to send email: {ex.Message}");
            }
        }
    }


    public class UserApplicationData
    {
        public string Nickname { get; set; }
        public byte[] Image { get; set; }
        public int Finished { get; set; }
        public int Approved { get; set; }

        public int Id { get; set; }
    }
    public class ApplicantModel : PageModel
    {

        private readonly ILogger<ApplicantModel> _logger;

        public ApplicantModel(ILogger<ApplicantModel> logger)
        {
            _logger = logger;
        }
        public int groupId;
        public int MemberCount;
        public void OnGet()
        {
            ViewData["Page"] = "Show";

            if (int.TryParse(Request.Query["GroupId"], out int parsedGroupId))
            {
                groupId = parsedGroupId;
            }
            string connectionString = "Server=localhost;Database=ZEUS;Uid=root;Pwd=azxcvbnmlkjhgfds;";
            string query = $"SELECT UserId FROM Applications WHERE GroupId = {groupId}";
            string queryMember = $"SELECT Members FROM Usersgroups WHERE UserId = {groupId}";
            List<int> userIds = new();

            MySqlConnection mySqlConnection = new(connectionString);
            using MySqlConnection connection = mySqlConnection;
            connection.Open();

            var command = new MySqlCommand(query, connection);
            MySqlCommand command_1 = new(queryMember, connection);

            using (MySqlDataReader reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    int userId = reader.GetInt32("UserId");
                    userIds.Add(userId);
                }
            }

            using (MySqlDataReader reader = command_1.ExecuteReader())
            {
                while (reader.Read())
                {
                    MemberCount = reader.GetInt32("Members");
                }
            }

            List<UserApplicationData> userApplications = new();

            foreach (int userId in userIds)
            {
                string userQuery = $"SELECT Nickname, Id, Image, Finished, Approved FROM Users WHERE Id = {userId}";

                using MySqlCommand userCommand = new(userQuery, connection);
                MySqlDataReader mySqlDataReader = userCommand.ExecuteReader();
                using MySqlDataReader userReader = mySqlDataReader;
                while (userReader.Read())
                {
                    UserApplicationData userApplication = new()
                    {
                        Nickname = userReader.GetString("Nickname"),
                        Image = (byte[])userReader["Image"],
                        Finished = userReader.GetInt32("Finished"),
                        Approved = userReader.GetInt32("Approved"),
                        Id = userReader.GetInt32("Id")
                    };

                    userApplications.Add(userApplication);
                }
            }

            ViewData["UserApplications"] = userApplications;
        }

        public IActionResult OnPostAccept()
        {
            string connectionString = "Server=localhost;Database=ZEUS;Uid=root;Pwd=azxcvbnmlkjhgfds;";
            int applicantId = int.Parse(Request.Form["applicantId"]);
            int group = int.Parse(Request.Form["groupId"]);

            if (applicantId == 0 || group == 0)
            {
                return RedirectToPage("/Null");
            }



            using var connection = new MySqlConnection(connectionString);
            connection.Open();

            var updateQuery = "UPDATE Usersgroups SET Project = Project + (SELECT Finished FROM Users WHERE Id = @applicantId), Members = Members + 1 WHERE UserId = @groupId";

            using var command = new MySqlCommand(updateQuery, connection);
            command.Parameters.AddWithValue("@applicantId", applicantId);
            command.Parameters.AddWithValue("@groupId", group);

            int rowsAffected = command.ExecuteNonQuery();
            if (rowsAffected > 0)

            {

                var insertQuery = "INSERT INTO mygroup (GroupId, UserId) VALUES (@groupId, @applicantId)";
                using (MySqlCommand insertCommand = new(insertQuery, connection))
                {
                    insertCommand.Parameters.AddWithValue("@groupId", group);
                    insertCommand.Parameters.AddWithValue("@applicantId", applicantId);
                    insertCommand.ExecuteNonQuery();
                }


                var deleteQuery = "DELETE FROM Applications WHERE UserId = @applicantId";
                using (var deleteCommand = new MySqlCommand(deleteQuery, connection))
                {
                    deleteCommand.Parameters.AddWithValue("@applicantId", applicantId);
                    deleteCommand.ExecuteNonQuery();
                }


                // this query will update the lastActivity column of the activity column
                string updateQuery1 = "UPDATE activity SET lastActivity = NOW() WHERE Id = @Id";

                using (var updateCommand = new MySqlCommand(updateQuery1, connection))
                {

                    // Set the parameter value
                    updateCommand.Parameters.AddWithValue("@Id", LoginModel.UserId);

                    // Execute the query to update the lastActivity column
                    updateCommand.ExecuteNonQuery();
                }

                return RedirectToPage("/Groups");
            }

            else
            {
                return RedirectToPage("/ErrorType");
            }


        }








        public IActionResult OnPostDelete()
        {
            string connectionString = "Server=localhost;Database=ZEUS;Uid=root;Pwd=azxcvbnmlkjhgfds;";

            // Retrieve the applicantId and groupId from the form
            if (int.TryParse(Request.Form["applicantId"], out int applicantId) &&
                int.TryParse(Request.Form["groupId"], out int groupId))
            {
                // Delete the applicant with the given ID from the Applications table
                // where UsersId matches the applicantId

                using var connection = new MySqlConnection(connectionString);
                connection.Open();

                var deleteQuery = "DELETE FROM Applications WHERE UserId = @applicantId";
                using var deleteCommand = new MySqlCommand(deleteQuery, connection);
                deleteCommand.Parameters.AddWithValue("@applicantId", applicantId);
                deleteCommand.ExecuteNonQuery();

                // Send an email notification to the recipient using the EmailSender
                string recipientEmail = GetRecipientEmail(connection, applicantId);
                string groupName = GetGroupName(connection, groupId);

                EmailData1 emailData = new EmailData1
                {
                    GroupName1 = groupName,
                    Subject = "Application not been accepted"
                };

                EmailSender1 emailSender = new EmailSender1();
                emailSender.SendEmail(recipientEmail, emailData);
            }

            // Redirect to the page
            return RedirectToPage("/Groups");
        }

        // Helper method to get recipient email from Signup table
        private string GetRecipientEmail(MySqlConnection connection, int applicantId)
        {
            string getEmailQuery = "SELECT Email FROM Signup WHERE Id = @applicantId";
            string recipientEmail = string.Empty;
            using (var getEmailCommand = new MySqlCommand(getEmailQuery, connection))
            {
                getEmailCommand.Parameters.AddWithValue("@applicantId", applicantId);
                using (var reader = getEmailCommand.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        recipientEmail = reader.GetString("Email");
                    }
                }
            }
            return recipientEmail;
        }

        // Helper method to get group name from usersgroups table

Enhance/Pages/Bids.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MySql.Data.MySqlClient;
using System.Collections.Generic;

namespace Enhance.Pages
{
    public class BidsModel : PageModel
    {
        public class Bided_Project
        {
            public int IdValue { get; set; }
            public string Bid { get; set; }
            public string Duration { get; set; }
            public string DurationType { get; set; }
            public int Number { get; set; }
            public int Status { get; set; }
        }

        public int Id = LoginModel.UserId;
        private string connectString = "Server=localhost;Database=ZEUS;Uid=root;Pwd=azxcvbnmlkjhgfds;";
        public List<Bided_Project>? BidedProjects { get; set; }

        public void OnGet()
        {
            ViewData["Page"] = "Show";
            BidedProjects = new List<Bided_Project>();

            using (var connection = new MySqlConnection(connectString))
            {
                connection.Open();

                string query = "SELECT Id, Project_Id, Bid, Duration, Status, DurationType FROM BID WHERE Id = @Id";
                using (var command = new MySqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@Id", Id);

                    using (var reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            BidedProjects.Add(new Bided_Project
                            {
                                IdValue = reader.GetInt32("Id"),
                                Number = reader.GetInt32("Project_Id"),
                                Bid = reader.GetString("Bid"),
                                Duration = reader.GetString("Duration"),
                                DurationType = reader.GetString("DurationType"),
                                Status = reader.GetInt32("Status")
                            });
                        }
                    }
                }
            }
        }
    }
}

Enhance/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Enhance.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Enhance/Pages/ErrorType.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Enhance.Pages
{
    public class ErrorTypeModel : PageModel
    {
        public void OnGet()
        {
            ViewData["Page"] = "Show";
        }
    }
}

Enhance/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Enhance.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            ViewData["Page"] = "Index";
            ViewData["Title"] = "Landing page";
        }
    }
}

Enhance/Pages/Null.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Enhance.Pages
{
    public class NullModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Enhance/Pages/AlreadyExist.cshtml
@page
@model Enhance.Pages.AlreadyExistModel
@{
    ViewData["Title"] = "Already exist";
}

<head>
    <link rel="stylesheet" href="~/css/AlreadyExist.css?version=1" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/AllProject.css?version=1" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Groups.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;300;400;500&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>


<a href="/Groups"><button>Back</button></a>

<h2>Ooops, seems like you are already in a group</h2>

Enhance/Pages/Applicant.cshtml
@page
@model Enhance.Pages.ApplicantModel
@{
    ViewData["Title"] = "Applications page";
}

<head>

    
    <link rel="stylesheet" href="~/css/AllProject.css?version=1" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Groups.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;300;400;500&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<h3>Applications</h3>




<div class="main" style="margin-top: 100px;">

    <div class="project">

        <div class="head">
        <div class="postDate">
            <h4>Image</h4>
        </div>
        <div class="price">
            <h4 style="margin-left: -25px;">Nickname</h4>
        </div>
        <div class="seeProject">
            <h4>Finished</h4>
        </div>
        <div class="seeBids">
            <h4>Approved</h4>
        </div>
        <div class="Apply">
            <h4>Accept</h4>
        </div>
        <div class="Apply">
            <h4>Reject</h4>
        </div>
        </div>
    </div>

    @if (ViewData["UserApplications"] is List<UserApplicationData> userApplications && userApplications.Count > 0)
    {
        foreach (var userApplication in userApplications)
        {
            <div class="project">
                <div class="postDate">
                    <a style="width" href="/Profile?Id=@userApplication.Id"><img src="data:image/png;base64,@Convert.ToBase64String(userApplication.Image)" alt="User Image" /></a>
                </div>
                <div class="price">
                    <p>@userApplication.Nickname</p>
                </div>
                <div class="seeProject">
                    <p>@userApplication.Finished</p>
                </div>
                <div class="seeBids">
                    <p>@userApplication.Approved</p>
                </div>

                <div class="Apply">
                    <form method="post" asp-page-handler="Accept">
                        <input type="hidden" name="groupId" value="@LoginModel.UserId"/>
                        <input type="hidden" name="applicantId" value="@userApplication.Id" />
                        <button type="submit" @(Model.MemberCount == 5 ? "disabled" : "")>Accept</button>
                    </form>
                </div>

                <div class="Apply">
                    <form method="post" asp-page-handler="Delete">
                        <input type="hidden" name="applicantId" value="@userApplication.Id" />
                        <button type="submit">Reject</button>
                    </form>
                </div>

            </div>
        }
    }
    else
    {
        <p>No user applications found.</p>
    }

</div>

Enhance/Pages/CardDetails.cshtml
@page
@model Enhance.Pages.CardDetailsModel


@{
    ViewData["Title"] = "Project Details";
}

<head>
    <link rel="stylesheet" href="~/css/CardDetails.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@300;400&display=swap" rel="stylesheet">
</head>


<h2 class="Heading">@Model.ProjectName</h2>


<div class="Duration_Post">

    <p> class="PostDate">Post Date - @Model.PostDate</p>

    <div class="Duration">
        <h3>Duration time and type</h3>
        <p>@Model.Duration @Model.DurationType</p>
    </div>
</div>

<div class="Description">
    <p>@Model.Description</p>
</div>

<div class="skills">
    <h4>Skill Required:</h4>
    <ul>
        @foreach (var skill in Model.SkillRequired)
        {
            <li>@skill</li>
        }
    </ul>
</div>


<form method="post">

    <div class="Bid_Duration">

        <div class="form-group Bid">

            <label for="email">Bid Amount:</label>
            <input type="text" name="Bid" id="bid" class="form-control" placeholder="Bid Amount" required
                autocomplete="off" />

        </div>



        <div class="form-group Duration_value">

            <label for="duration">Duration:</label>
            <input type="number" name="Duration" id="duration" class="form-control" placeholder="Duration" required
                autocomplete="off" />

        </div>

        <div class="form-group Duration">
            <label for="duration">Duration type:</label>
            <select class="form-select" asp-for="DurationType">
                <option value="Hour">Hour</option>
                <option value="Day">Day</option>
                <option value="Week">Week</option>
                <option value="Month">Month</option>
            </select>

        </div>

    </div>

    <div class="form-group Description">

        <label for="description">Description:</label>
        <textarea name="Description" id="description" placeholder="Description" required autocomplete="off"></textarea>

    </div>



    <input type="hidden" name="Project_Id" value="@Model.Number" />
    @{
        bool disableButton = (@Model.Exist || LoginModel.UserId == @Model.UserId);
    }
    <button type="submit" class="btn" @(disableButton || @Model.Status == 1 ? "disabled" : "")>Place Bid</button>

</form>

Enhance/Pages/Cards.cshtml
@page

@model Enhance.Pages.Shared.CardsModel
@{
    ViewData["Title"] = "Active projects";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Cards.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@300;400&display=swap" rel="stylesheet">
</head>




<div class="card-collection">
    @foreach (var project in Model.Projects)
    {

        <div class="card @(project.Check == 1 ? "hidden-card" : "")">



            <div class="user-info">
                <div class="user-check">
                    @if (project.ImageData != null)
                    {
                        <a href="/Profile?Id=@project.UserId"><img src="data:image/png;base64,@Convert.ToBase64String(project.ImageData)" alt="User Image" /></a>
                    }
                    else
                    {
                        <img src="~/Images/use.jpg" alt="User Image" />
                    }

                    

                    @foreach (var activeProject in Model.ActiveProjects)
                    {
                        @if (@activeProject.UserId == @project.UserId)
                        

                        {
                            
                            @if (activeProject.Active)
                            {
                                
                                <div class="active-check"></div>
                                
                            }
                            else
                            {

                                <div class="inactive-check"></div>
                            }
                        }
                    }



                </div>
                <h3>@project.ProjectName</h3>
            </div>


            <div class="Bid_Duration">
                <h4>Bid Amount - @project.Price @project.CurrencyType</h4>
                <p>Duration - @project.Duration  @project.DurationType</p>
            </div>



            <div class="card-mid">
                <p style="font-weight: bold; text-decoration: underline 2px solid black;">Description</p>
                <p>@project.Description</p>
            </div>


            <div class="card-bottom">
                <p>Post date - @project.PostDate</p>
            </div>


            <a href="/CardDetails?Number=@project.Number"><button>View details</button></a>

        </div>
    }
</div>

Enhance/Pages/Close.cshtml
@page
@model Enhance.Pages.CloseModel
@{
    ViewData["Title"] = "Close project";
}


<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/Close.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@300;400&display=swap" rel="stylesheet">
</head>

<img src="~/Images/Cube.png" alt="cube image for animations"/>

<div class="Ipfs">
    <form method="post">
        <label>The IPFS CID (Content Identifier) is a special code that uniquely identifies files and directories within the IPFS network. </label>
        <a href="https://docs.ipfs.tech/concepts/content-addressing/"><button class="know">Know about cid</button></a>
        <input type="text" autocomplete="off" placeholder="Enter the cid of the file " asp-for="Cid"/>
        <button type="Submit">Upload</button>
    </form>
</div>

Enhance/Pages/Creategroup.cshtml
@page
@model Enhance.Pages.CreategroupModel
@{
    ViewData["Title"] = "Create Group page";
}

<head>
    <link rel="stylesheet" href="~/css/Creategroup.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;300;400;500&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<form method="post">
    <div class="Name">
        <input type="text" placeholder="Enter group name" autocomplete="off" asp-for="Name"/>
    </div>
    <button type="submit">Create</button>
</form>

<!--<img src="~/Images/Creategroup.png"/>-->

Enhance/Pages/EnrolledGroup.cshtml
@page
@model Enhance.Pages.EnrolledGroupModel
@{
    ViewData["Title"] = "Enrolled group page";
}

<head>

    <link rel="stylesheet" href="~/css/MYgroup.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;300;400;500&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>


<h2>Members of you're group</h2>

<!-- this here we will show all those people who are the part of the group created by us -->
<div class="user-data-col">
    <div class="user-data1">




        <h6>Image</h6>
        <h6>Nickname</h6>
        <h6>Country</h6>
        <h6>Dob</h6>
        <h6>Approved</h6>
        <h6>Finished</h6>
        
    </div>
    @foreach (var userApplication in Model.UserApplications)
    {

        <div class="user-data">



            @if (userApplication.Image != null)
            {
                <a href="/Profile?Id=@userApplication.Id"><img src="data:image/png;base64,@Convert.ToBase64String(userApplication.Image)" alt="User Image" /></a>
            }
            else
            {
                <img src="~/Images/use.jpg" alt="User Image" />
            }
            <h4>@userApplication.Nickname</h4>
            <p>@userApplication.Country</p>
            <h5>@userApplication.Dob</h5>
            <p>@userApplication.Approved</p>
            <p>@userApplication.Finished</p>
            
        </div>

    }
</div>

Enhance/Pages/ErrorType.cshtml
@page
@model Enhance.Pages.ErrorTypeModel
@{
    ViewData["Title"] = "Error page";
}

<head>
    <link rel="stylesheet" href="~/css/AllProject.css?version=1" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Groups.css?version=1" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;300;400;500&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<p>
    error in not having any row effected
</p>